### ISSUE TITLE
Missing Notification class

### ISSUE THREAD

**Issue by rodber** [chevereto/chevereto#10]
![13](https://user-images.githubusercontent.com/39656612/218924234-777d140f-3608-4de1-835f-3454e1c84d0a.jpg)

[chevereto-error.log](https://github.com/chevereto/chevereto/files/10739054/chevereto-error.log)

Relevant log has been uploaded

_Originally posted by @cnjsyyb in https://github.com/chevereto/chevereto/discussions/9#discussioncomment-4977846_

**Comment by eyahlin** [comment]
Hi! Thanks for updating to 4.0.8. I've upgraded to it. Unfortunately, the error still displays when I try to delete an image:

![image](https://github.com/chevereto/chevereto/assets/17564665/3cd3796d-de96-4c9f-befa-ff2672fb748f)
