### ISSUE TITLE
Installed from free v3 to AGPL v4 - now it acts like a single user website?

### ISSUE THREAD

**Issue by accessiblepixel** [chevereto/chevereto#22]
I'm not sure if this is right, but upgrading from free to the AGPL v4 code from github and it only shows my profile, not any of the other users on the instance?

It doesn't match the screenshots that appear in the repo and trying to even view other users registered on the system is "locked" behind a pro license?

Is all accessible functionality now locked behind the 67$ license or have I just encountered a bug?

Kind regards,

**Comment by rodber** [comment]
The project at [rodber/chevereto-free](https://github.com/rodber/chevereto-free) doesn't share functionality with the project I run here. I wrote about this in [this post](https://rodolfoberrios.com/2022/12/01/chevereto-goes-free/).
