### ISSUE TITLE
Public Demo

### ISSUE THREAD

**Issue by meichthys** [chevereto/chevereto#24]
It would be really nice if there was a public demo that could be used to get a quick feel of the application. 

It would also be very helpful for me to keep https://github.com/meichthys/foss_photo_libraries up to date.

**Comment by rodber** [comment]
Chevereto has two editions, free (this repo) and pro (chevereto.com). This project here is auto sourced from the same base branch, but this fork contain less features.

The demo at https://demo.chevereto.com/ should meet your needs.

**Comment by meichthys** [comment]
@rodber Is there a way to disable the pro features in the demo? Ideally for comparison sake in https://github.com/meichthys/foss_photo_libraries, I'm trying to  focus on the free version.

**Comment by rodber** [comment]
I've reviewed this request and I will say no to provide a public demo.

1. We already provide hosted demos at chevereto.com where you can get a 3-day paid/free private demo
2. A public demo will require to review the content served/exposed, re-set demo, etc. All that trouble for free tier users?
3. You can get a local demo in less than one minute when running docker

For the above reasons I will close this issue. I suggest you to either run a local demo or ask for a hosted demo all the times you want.

**Comment by meichthys** [comment]
Completely understandable. Thanks for considering 👍
