### ISSUE TITLE
Missing Notification Class when Deleting a Picture or Album

### ISSUE THREAD

**Issue by eyahlin** [chevereto/chevereto#29]
Hi! First off, thanks for creating Chevereto. It is an awesome piece of software =)

I am creating a new issue [in reference to an old one](https://github.com/chevereto/chevereto/issues/10), because it unfortunately still hasn't been resolved in the new update. 

Basically, I encounter this error whenever I try to delete a picture or album:

![image](https://github.com/chevereto/chevereto/assets/17564665/538abfb0-3bc2-4093-9625-530536b5b751)

Continuing to click "Confirm" just makes the Notification error pop up (shake):

``Class "Chevereto\Legacy\Classes\Notification" not found (0)``

After refreshing the page, I would see that the image still exists in the gallery, but it already has an "empty inbox" icon:

![image](https://github.com/chevereto/chevereto/assets/17564665/7abba47f-3c6d-4f0e-b92f-d417cf697033)

And when I click on the image to expand it, I get this:

![image](https://github.com/chevereto/chevereto/assets/17564665/e2085a32-6a44-497c-bbc6-002ab4a3e511)

That means that while the image has already (probably) been deleted, it still appears in the list. Couuld the error message regarding ``Notification`` be a clue?

Keep up the good work!

**Comment by rodber** [comment]
`Notification` class in `chevereto/chevereto` is just a dummy class:

app/src/Legacy/Classes/Notification.php

```php
<?php

/*
 * This file is part of Chevereto.
 *
 * (c) Rodolfo Berrios <rodolfo@chevereto.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Chevereto\Legacy\Classes;

class Notification
{
    public static array $content_types = ['image', 'album', 'like', 'follow'];

    public static function get(array $args = []): array
    {
        return [];
    }

    public static function insert(array $args = []): void
    {
    }

    public static function delete(array $args = []): void
    {
    }

    public static function markAsRead(array $args = []): void
    {
    }

    protected static function fill(array &$row): void
    {
    }

    protected static function hasContent(array $row): bool
    {
        return false;
    }
}
```

I forgot to add the file reference to the free edition builder.

**Comment by eyahlin** [comment]
Thanks for the response! Where should I put this file? Do we need to edit anything else?

**Comment by rodber** [comment]
@eyahlin I've explicit indicated a path in my comment. Besides that, your will need to dump composer autoload.
I suggest you to wait until I release `4.0.9` when this issue will get patched.

**Comment by eyahlin** [comment]
Noted! I'll wait for the next release. Thank you very much. =)

**Comment by eyahlin** [comment]
After downloading the `Notification.php` file to `app/src/Legacy/Classes/`, I changed the directory to `app/` and ran this command: `composer upgrade`. It works now =)

**Comment by eyahlin** [comment]
After downloading the `Notification.php` file to `app/src/Legacy/Classes/`, I changed the directory to `app/` and ran this command: `composer upgrade`. It works now =)
