### ISSUE TITLE
Unable to install 4.0.5 version

### ISSUE THREAD

**Issue by shree0** [chevereto/chevereto#3]
Hello, 
I am trying to install chevereto 4.0.5 version using PHP 8.0 and PHP 8.1 version. But during 1st step of the installation, I got the `Something went wrong` error. I am not getting the exact error to debug it. 
I have created `env.php` inside` ...//app` folder and added the following:
<?php

return [
  'CHEVERETO_DB_NAME' => 'chevereto',
  'CHEVERETO_DB_PASS' => 'user_database_password',
  'CHEVERETO_DB_PORT' => '3306',
  'CHEVERETO_DB_TABLE_PREFIX' => 'chv_',
  'CHEVERETO_DB_USER' => 'user_database',
];

(replaced my database values with it). 

Please help how to resolve my issue.
Thanks.

**Comment by rodber** [comment]
Hi @shree0 

Refer to this message: https://chevereto.com/community/threads/re-something-went-wrong.14550/
(You need to debug to determine the actual error).

P.S. Happy new year!

**Comment by shree0** [comment]
Happy new year.

I have tried to install it in my Cpanel. After I create the `env.php` file I am getting the following errors. (If I put values to `env.php` I am getting a `Not Found` error.)

Errors in the Cpanel error log:
../index.php:12

.../app/legacy/entrypoints/index.php:25

.../app/src/Legacy/functions.php:979

..../app/vendor/chevere/chevere/src/Filesystem/FilePhpReturn.php:75

..../app/vendor/chevere/chevere/src/Filesystem/FilePhpReturn.php:70

..../app/vendor/chevere/chevere/src/Filesystem/FilePhpReturn.php:56

..../app/vendor/chevere/chevere/src/Filesystem/FilePhpReturn.php:126

..../app/env.php doesn't have any contents

Chevere\\Filesystem\\Exceptions\\FileWithoutContentsException thrown in .../app/vendor/chevere/chevere/src/Filesystem/FilePhpReturn.php:126

**Comment by rodber** [comment]
https://v4-docs.chevereto.com/guides/cpanel/
