### ISSUE TITLE
Version number not updated in 4.0.9 zip

### ISSUE THREAD

**Issue by prbt2016** [chevereto/chevereto#32]
Hello @rodber ,

I was in the process of manual installation of Chevereto 4.0.9 on Centos 7 with  PHP 8.0, MYSQL 5.7, Apache 2.4 downloaded from 

https://github.com/chevereto/chevereto/releases/download/4.0.9/4.0.9.zip

However ,t seems that version number is not updated in file app/legacy/load/app.php, under line 12 i.e : 
`const APP_VERSION = '4.0.8';`

it is still 4.0.8.

Due to this under dashboard it shows 4.0.8 : 

![Screenshot 2023-08-29 at 13-52-08 Chevereto image hosting](https://github.com/chevereto/chevereto/assets/17871448/9d70806e-130f-4bf3-864b-b2a7e281480b)

Also under database it is not updated under `settings`  table i.e : 
`(3, 'chevereto_version_installed', '4.0.8', '4.0.8', 'string'),`

Could you please check fix this?.

**Comment by rodber** [comment]
File updated.

**Comment by prbt2016** [comment]
Hello @rodber ,

Got it . Thanks a lot :+1: 

Regards.
