### ISSUE TITLE
The uploaded image cannot be accessed

### ISSUE THREAD

**Issue by SagitTariuse** [chevereto/chevereto#35]
I managed to upload a picture,There is no problem with my domain name
![image](https://github.com/chevereto/chevereto/assets/81310072/6e47d062-1262-4de5-bc64-b233e13c5a43)

Image not accessible
![image](https://github.com/chevereto/chevereto/assets/81310072/43b919f1-d0c8-4dc1-ae8e-e87b14c62229)

However, the http link in markdown is accessible
![image](https://github.com/chevereto/chevereto/assets/81310072/5cce3152-c1d9-4d50-99f5-7e7074098785)

**Comment by rodber** [comment]
Do not re-open a new issue for this.

https://github.com/chevereto/chevereto/discussions/34
