### ISSUE TITLE
Why ids are used with implodes in queries?

### ISSUE THREAD

**Issue by bradparks** [chevereto/chevereto#45]
![image](https://github.com/chevereto/chevereto/assets/185477/44c92e70-9b77-4132-b1f1-0235d49c9a3b)

Hey... I'm wondering why you're using sprintf, implodes and concatting strings here to build sql queries?
if any of the ids that are being used in these queries were user supplied, can't they be a sql injection?

I see at times you're using parameters and I get that the table names are under your control, but the ids I find surprising? 

Thanks for your time :D !

**Comment by rodber** [comment]
This codebase is filled with a ridiculous amount of ways to do things as it is a reflection of my experimentation during the first leg of my career.

I did many wacky things back in the day, but it works!
